package kr.ac.kaist.se.data;

import java.sql.Timestamp;

/**
 * Class to define a log event from simulation execution.
 * An object (instance) of this class will be generated by calling run() method of SimObject
 * @author ymbaek
 */
public class SimLogEvent {
    protected Timestamp timestamp;    //Timestamp for stdout

    protected String id;                //id of an event
    protected String name;              //name of an event (used as a label)
    protected EnumEventType eventType;   //type of an event
}
